
services:
  gitea:
    container_name: gitea
    image: gitea/gitea:1.21.4
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=giteadb:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=devops
      - GITEA__database__PASSWD=P@ssw0rd
      - GITEA__webhook__ALLOWED_HOST_LIST=*
    restart: always
    ports:
      - 9000:3000
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - devops-network

  giteadb:
    container_name: giteadb
    image: postgres:16.1-bullseye
    restart: always
      #ports:
      #  - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
    volumes:
      - ./pg-data:/var/lib/postgresql/data
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    networks:
      - devops-network

networks:
  devops-network:
    external: true
