services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:2.444-jdk17
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
    networks:
      - devops-network

networks:
  devops-network:
    external: true
