services:
  jenkins:
    container_name: jenkins
    image: jenkins:2.444-jdk17
    ports:
      - 9001:8080
      - 50000:50000
    restart: always
    volumes:
      - ./jenkins_home:/var/jenkins_home
    networks:
      - devops-network

networks:
  devops-network:
    external: true
