---
- name: Install Jenkins
  hosts: utilities
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Create Jenkins Directory
      ansible.builtin.shell: |
        mkdir -p ~/jenkins/jenkins_home 
        sudo chown -R 1000:1000 ~/jenkins/jenkins_home

    - name: Copy Docker Compose file
      ansible.builtin.copy:
        src: docker-compose.yml
        dest: ~/jenkins/docker-compose.yml

    - name: Copy Docker file
      ansible.builtin.copy:
        src: Dockerfile
        dest: ~/jenkins/Dockerfile
          
    - name: Download Image
      ansible.builtin.shell: |
        docker pull jenkins/jenkins:2.444-jdk17

    - name: Build Image
      ansible.builtin.shell:
        chdir: ~/jenkins
        cmd: docker build -t jenkins:2.444-jdk17 .

    - name: Start Jenkins
      ansible.builtin.shell:
        chdir: ~/jenkins
        cmd: docker compose up -d
