services:
  sonar:
    container_name: sonarqube
    image: sonarqube:9.9.4-community
    ports:
      - 9000:9000
    restart: always
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://devopsdb:5432/sonar?currentSchema=public
      - SONAR_JDBC_USERNAME=devops
      - SONAR_JDBC_PASSWORD=P@ssw0rd
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
        #user: "$UID:$GID"
    networks:
      - devops-network

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:

networks:
  devops-network:
    external: true
