---
- name: Install Sonarqube
  hosts: utilities
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Create Jenkins Directory
      ansible.builtin.shell: |
        mkdir -p ~/sonar

    - name: Copy Docker Compose file
      ansible.builtin.copy:
        src: docker-compose.yml
        dest: ~/sonar/docker-compose.yml
          
    - name: Copy User Db Init  file
      ansible.builtin.copy:
        src: init-user-db.sh
        dest: ~/sonar/init-user-db.sh


    - name: Download Image
      ansible.builtin.shell: |
        # docker pull sonarqube:9.9.4-community
        docker pull sonarqube:8.9.10-community

    - name: Start Sonarqube
      ansible.builtin.shell:
        chdir: ~/sonar
        cmd: docker compose up -d
