services:
  grafana:
    container_name: grafana
    image: grafana/grafana-oss:10.3.1-ubuntu
    ports:
      - 3001:3000
    restart: always
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_SERVER_PROTOCOL=http
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=devopsdb:5432
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_USER=devops
      - GF_DATABASE_PASSWORD=P@ssw0rd
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./ds.yaml:/etc/grafana/provisioning/datasources/ds.yaml
    user: "$UID:$GID"
    networks:
      - devops-network

  loki:
    container_name: loki
    image: grafana/loki:2.9.4
    ports:
      - 3100:3100
    volumes:
      - ./loki-config.yml:/etc/loki/config.yml
    networks:
      - devops-network

networks:
  devops-network:
    external: true
