---
- name: Install Grafana
  hosts: utilities
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Create Grafana Directory
      ansible.builtin.shell: |
        mkdir -p ~/grafana

    - name: Copy Docker Compose file
      ansible.builtin.copy:
        src: docker-compose.yml
        dest: ~/grafana/docker-compose.yml

    - name: Copy Datasource file
      ansible.builtin.copy:
        src: ds.yaml
        dest: ~/grafana/ds.yaml

    - name: Copy Loki Configuration file
      ansible.builtin.copy:
        src: loki-config.yml
        dest: ~/grafana/loki.yml
          
    - name: Download Image
      ansible.builtin.shell: |
       docker pull grafana/grafana-oss:10.3.1-ubuntu
       docker pull grafana/loki:2.9.4
         
    - name: Start Jenkins
      ansible.builtin.shell:
        chdir: ~/grafana
        cmd: docker compose up -d
