services:
  proxy:
    image: nginx:1.25.3
    ports:
      - "80:80"
      - "443:443"
      - "5000:5000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d

